vich_uploader:
    db_driver: orm

    mappings:
        articles:
            uri_prefix: /images/articles
            upload_destination: '%kernel.project_dir%/public/images/articles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        
        projets: 
            uri_prefix: /images/projets
            upload_destination: '%kernel.project_dir%/public/images/projets'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer